name: Cypress Tests

on:
 push:
  branches:
  - "main"
  - "master"
 workflow_dispatch:

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Node
              uses: actions/setup-node@v3
              with:
               node-version: 14
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm start
                  record: true
              env:
                  CYPRESS_RECORD_KEY: 6baa811f-9969-4735-874d-be61d857df63
