name: Cypress Tests

on:
    push:
        branches:
            - "main"
            - "master"
    workflow_dispatch:

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Node
              uses: actions/setup-node@v3
              with:
                  node-version: 14
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Install Stripe CLI
              run: curl -L https://github.com/stripe/stripe-cli/releases/download/v1.13.5/stripe_1.13.5_linux_x86_64.tar.gz --output stripe.tar.gz && tar -xvf stripe.tar.gz
            - name: Start Stripe CLI
              run: export PATH=$PATH:/home/runner/work/DNANutrition/DNANutrition stripe listen --api-key ${{ secrets.STRIPE_SECRET_KEY }} --forward-to http://localhost:3000/api/markAsPaid &
            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm start
                  record: true
              env:
                  CYPRESS_RECORD_KEY: 6baa811f-9969-4735-874d-be61d857df63
                  MONGO_URI: ${{ secrets.MONGO_URI }}
                  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
                  CLOVER_URL_SCL: ${{ secrets.CLOVER_URL_SCL }}
                  CLOVER_URL_API: ${{ secrets.CLOVER_URL_API }}
                  CLOVER_MERCHANT_ID: ${{ secrets.CLOVER_MERCHANT_ID }}
                  CLOVER_TOKEN: ${{ secrets.CLOVER_TOKEN }}
                  CLOVER_ECOMMERCE: ${{ secrets.CLOVER_ECOMMERCE }}
                  STRIPE_SHIPPING: ${{ secrets.STRIPE_SHIPPING }}
                  STRIPE_TAX_RATE: ${{ secrets.STRIPE_TAX_RATE }}
                  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
                  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
                  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
                  PRODUCTS_URL: ${{ secrets.PRODUCTS_URL }}
                  TEST_ENV: true
