name: Cypress Tests

on:
    push:
        branches:
            - "main"
            - "master"
    workflow_dispatch:

jobs:
    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Node
              uses: actions/setup-node@v3
              with:
                  node-version: 14
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: Install Stripe CLI
              run: curl -s https://packages.stripe.dev/api/security/keypair/stripe-cli-gpg/public | gpg --dearmor | sudo tee /usr/share/keyrings/stripe.gpg && echo "deb [signed-by=/usr/share/keyrings/stripe.gpg] https://packages.stripe.dev/stripe-cli-debian-local stable main" | sudo tee -a /etc/apt/sources.list.d/stripe.list && sudo apt update && sudo apt install stripe

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  build: npm run build
                  start: npm start
                  record: true
              env:
                  CYPRESS_RECORD_KEY: 6baa811f-9969-4735-874d-be61d857df63
                  MONGO_URI: ${{ secrets.MONGO_URI }}
                  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
                  CLOVER_URL_SCL: ${{ secrets.CLOVER_URL_SCL }}
                  CLOVER_URL_API: ${{ secrets.CLOVER_URL_API }}
                  CLOVER_MERCHANT_ID: ${{ secrets.CLOVER_MERCHANT_ID }}
                  CLOVER_TOKEN: ${{ secrets.CLOVER_TOKEN }}
                  CLOVER_ECOMMERCE: ${{ secrets.CLOVER_ECOMMERCE }}
                  STRIPE_SHIPPING: ${{ secrets.STRIPE_SHIPPING }}
                  STRIPE_TAX_RATE: ${{ secrets.STRIPE_TAX_RATE }}
                  STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
                  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
                  SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
                  PRODUCTS_URL: ${{ secrets.PRODUCTS_URL }}
                  TEST_ENV: true
